### ISSUE TITLE
Reactions API

### ISSUE THREAD

**Issue by TIBseqlab** [kingstdio/brem#1]
1. 拉取反应的API需要更新，目前蛋白搜索后，上面的API拉倒的反应是对的，但下面相似蛋白拉反应的API有问题。例子：P04693
2. 反应对应的EC号，需要根据数据库直接拉取，目前是根据蛋白EC号组合的

**Comment by kingstdio** [comment]
1. issue updated

**Comment by kingstdio** [comment]
2 issue updated
